server:
  host: "localhost"
  port: "3000"

database:
  host: "localhost"
  port: "5432"
  user: "postgres"
  password: "postgres"
  dbname: "transjakarta_fleet"
  sslmode: "disable"

mqtt:
  broker: "localhost"
  port: "1883"
  username: ""
  password: ""

rabbitmq:
  url: "amqp://guest:guest@localhost:5672/"
  exchange: "fleet.events"
  queue: "geofence_alerts"