server:
  host: "0.0.0.0"
  port: "3000"

database:
  host: "postgres"
  port: "5432"
  user: "postgres"
  password: "postgres"
  dbname: "transjakarta_fleet"
  sslmode: "disable"

mqtt:
  broker: "mosquitto"
  port: "1883"
  username: ""
  password: ""

rabbitmq:
  url: "amqp://guest:guest@rabbitmq:5672/"
  exchange: "fleet.events"
  queue: "geofence_alerts"